name: "CI - Test Features"
on:
    push:
        branches:
            - main
    pull_request:
    workflow_dispatch:

jobs:
    test-noir-barretenberg:
        runs-on: ubuntu-latest
        continue-on-error: true
        steps:
            - uses: actions/checkout@v4

            - name: "Install latest devcontainer CLI"
              run: npm install -g @devcontainers/cli

            - name: "Testing global scenarios"
              run: devcontainer features test -f noir_barretenberg

    test-aztec-sandbox:
        runs-on: ubuntu-latest
        continue-on-error: true
        steps:
            - uses: actions/checkout@v4

            - name: "Install latest devcontainer CLI"
              run: npm install -g @devcontainers/cli

            - name: "Testing aztec-sandbox feature"
              run: devcontainer features test -f aztec-sandbox
